src/coin/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),  # 처음 메인 화면 뷰
    path('chat_rooms/', views.chat_rooms, name='chat_rooms'),  # 채팅방 목록 뷰
    path('create_chat_room/', views.create_chat_room, name='create_chat_room'),  # 새 채팅방 생성 뷰
    path('<str:room_name>/', views.room, name='room'),  # 채팅방 뷰
    
]

src/coin/coin/urls.py
from django.contrib import admin
from django.urls import path, include
from cobo import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('playcrypto/', include('playcrypto.urls')),
    path('common/', include('common.urls')),
    path('cobo/', include('cobo.urls')),
    path('chat/', include('chat.urls')),
    path('', views.index, name='index'), 
    # path('', include('cobo.urls')),
]

src/coin/chat/models.py
from django.db import models

class ChatRoom(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name

src/coin/chat/forms.py
# chat/forms.py
from django import forms
from .models import ChatRoom

class ChatRoomForm(forms.ModelForm):
    class Meta:
        model = ChatRoom
        fields = ['name']

src/coin/chat/views.py
from django.shortcuts import render, redirect
from .models import ChatRoom
from .forms import ChatRoomForm
from django.contrib.auth.decorators import login_required


@login_required(login_url='common:login')  # 로그인된 사용자만 접근 가능
def create_chat_room(request):
    if request.method == 'POST':
        room_name = request.POST.get('room_name')
        chat_room = ChatRoom.objects.create(name=room_name)
        return redirect('chat:index')
    return redirect('chat:index')

@login_required(login_url='common:login')  # 로그인된 사용자만 접근 가능
def index(request):
    chat_rooms = ChatRoom.objects.all()
    return render(request, 'chat/index.html', {'chat_rooms': chat_rooms})


def room(request, room_name):
    return render(request, "chat/room.html", {"room_name": room_name})


def chat_rooms(request):
    chat_rooms = ChatRoom.objects.all()
    return render(request, 'chat/chat_rooms.html', {'chat_rooms': chat_rooms})

src/coin/templates/chat/chat_rooms.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="layoutSidenav_content">
<main>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
    <tbody>
        <h1>Chat Rooms</h1>
        <ul>
            {% for chat_room in chat_rooms %}
                <li><a href="{% url 'chat:room' chat_room.name %}">{{ chat_room.name }}</a></li>
            {% endfor %}
        </ul>
    </tbody>
</main>
{% endblock %}

src/coin/templates/chat/create_chat_room.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1>Create Chat Room</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
{% endblock %}

src/coin/templates/chat/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="layoutSidenav_content">

<main>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
    <tbody>
        <h1>What chat room would you like to enter?</h1>
        <form method="post" action="{% url 'chat:create_chat_room' %}">
            {% csrf_token %}
            <input type="text" name="room_name" placeholder="Enter Room Name">
            <button type="submit">Create Room</button>
        </form>
        <h2>Chat Rooms</h2>
        <ul>
            {% for chat_room in chat_rooms %}
                {% if chat_room.name %}
                    <li><a href="{% url 'chat:room' chat_room.name %}">{{ chat_room.name }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>
    </tbody>
</main>
{% endblock %}

src/coin/templates/chat/room.html
<!-- chat/templates/chat/room.html -->

{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="layoutSidenav_content">

<main>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
    

<tbody>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}   
</tbody>
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</main>
{% endblock %}